# Generated by Django 5.2.7 on 2025-10-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_id', models.CharField(blank=True, max_length=50)),
                ('type_label', models.CharField(blank=True, max_length=200)),
                ('site_text', models.CharField(blank=True, max_length=400)),
                ('phone_display', models.CharField(blank=True, max_length=200)),
                ('whatsapp_raw', models.CharField(blank=True, help_text='Comma-separated numbers, e.g. 85515519825,85511223344', max_length=500)),
                ('complain_text', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
    ]
