# Generated by Django 5.2.7 on 2025-10-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='site_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='whatsapp_raw',
            field=models.CharField(blank=True, help_text='Comma-separated digits only numbers, e.g. 85515519825,85511223344', max_length=500),
        ),
    ]
