# Generated by Django 5.2.7 on 2025-10-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_whatsappnumber_whatsapppointer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WhatsAppNumber',
        ),
        migrations.DeleteModel(
            name='WhatsAppPointer',
        ),
    ]
