# Generated by Django 5.2.7 on 2025-10-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_globalwhatsapp_delete_whatsappnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalwhatsapp',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='globalwhatsapp',
            name='number',
        ),
        migrations.AddField(
            model_name='globalwhatsapp',
            name='numbers',
            field=models.TextField(default=[], help_text='Add multiple WhatsApp numbers, one per line'),
            preserve_default=False,
        ),
    ]
