# Generated by Django 5.2.7 on 2025-10-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_remove_globalwhatsapp_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='whatsapp_raw',
        ),
    ]
